1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota
- El array de 2 dimensiones debe ser de 2 filas y 3 columnas
- El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [32]:
# importamos numpy
import numpy as np

In [6]:
# metodo básico, para crear un array de una dimension
array1 = np.array([1, 2])
print(array1)
print(array1.ndim)

[1 2]
1


In [12]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)
print(array2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
array3 = np.array([[[1,2,3],[4,5,6]],[[2,7,1],[4,5,6]]])
print(array3)
print(array3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[2 7 1]
  [4 5 6]]]
3


2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [19]:
print(array1.ndim)
print(array1.size)
print(array1.shape)
print(array1.dtype)
print('.........')
print(array2.ndim)
print(array2.size)
print(array2.shape)
print(array2.dtype)
print('.........')
print(array3.ndim)
print(array3.size)
print(array3.shape)
print(array3.dtype)

1
2
(2,)
int64
.........
2
6
(2, 3)
int64
.........
3
12
(2, 2, 3)
int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [21]:
array4 = np.random.randint(0,27, (3,3))
print(array4)
print(array4.shape)

[[23  6 21]
 [ 3 17  7]
 [13  1 11]]
(3, 3)


4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [22]:
array5 = np.ones_like(array3)
print(array5)
print(array5.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


5. Es el momento de hacer algunas operaciones entre arrays
- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
Dividid las dos matricess

In [27]:
array6 = np.add(array2, array2)
print(array6)
# si se pueden sumar porque tienen la misma forma exactamente

[[ 2  4  6]
 [ 8 10 12]]


In [30]:
# creamos la matriz identidad
m_identidad = np.identity(3)
print(m_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# no se puede hacer la multiplicacion porque tienen formas diferentes, tenemos que crear un nuevo array
array8 = np.array([[2,2,2], [2,2,2], [2,2,2]])
print(array8)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [36]:
multiplicacion = np.multiply(m_identidad, array8)
print(multiplicacion)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [40]:
division2 = np.divide(m_identidad, array8)
print(division2)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [39]:
division1 = np.divide(array8, m_identidad)
print(division1)
print('No se puede dividier entre cero')

[[ 2. inf inf]
 [inf  2. inf]
 [inf inf  2.]]
No se puede dividier entre cero


/tmp/ipykernel_366/1761068861.py:1: RuntimeWarning: divide by zero encountered in divide
  division1 = np.divide(array8, m_identidad)
