In [25]:
import numpy as np
import pandas as pd


Ejercicio1-Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
 -El valor de la primera fila y la segunda columna.


In [26]:
array = np.random.rand(5,3) 
print(array)

[[0.56153125 0.66927805 0.6537926 ]
 [0.07209907 0.72554582 0.26021165]
 [0.48174959 0.65768893 0.79820328]
 [0.71824678 0.55617445 0.86814572]
 [0.7335052  0.49499387 0.16591643]]


In [27]:
array[0,1]

0.6692780463446395

1.1 Los valores de la segunda fila y las dos primeras columnas.

In [28]:
array[1,:2]

array([0.07209907, 0.72554582])

1.2 Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [29]:
array[::2,:]

array([[0.56153125, 0.66927805, 0.6537926 ],
       [0.48174959, 0.65768893, 0.79820328],
       [0.7335052 , 0.49499387, 0.16591643]])

1.3 Extraed los valores que sean mayores que 0.5.

In [30]:
array[array > 0.5]

array([0.56153125, 0.66927805, 0.6537926 , 0.72554582, 0.65768893,
       0.79820328, 0.71824678, 0.55617445, 0.86814572, 0.7335052 ])

1.4 Extraed los valores menores que 0.2 o mayores que 0.5

In [31]:
array[(array<0.2)|(array>0.5)]

array([0.56153125, 0.66927805, 0.6537926 , 0.07209907, 0.72554582,
       0.65768893, 0.79820328, 0.71824678, 0.55617445, 0.86814572,
       0.7335052 , 0.16591643])

Ejercicio2-Cread dos array de tres dimensiones:

2.1 El primero de 2 matrices, 5 filas y 3 columnas.

In [33]:
array1 = np.random.randint(0,9,(2,5,3))
print(array1)

[[[1 7 5]
  [7 5 3]
  [4 4 6]
  [6 3 3]
  [0 3 7]]

 [[3 5 5]
  [0 4 2]
  [7 6 5]
  [2 4 7]
  [1 7 5]]]


2.2 El segundo de 3 matrices, 2 filas y 5 columnas

In [34]:
array2 = np.random.randint(0,9,(3,2,5))
print(array2)

[[[1 0 6 4 3]
  [4 4 3 4 7]]

 [[5 7 7 0 3]
  [2 1 2 8 4]]

 [[8 8 2 0 5]
  [0 2 7 3 6]]]


2.3 Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [40]:
def analisis(miarray):
    return miarray.shape, miarray.size, miarray.dtype
    
    

In [43]:
print(analisis(array1))

analisis(array2)

((2, 5, 3), 30, dtype('int64'))


((3, 2, 5), 30, dtype('int64'))

2.4 Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [ ]:
# no se puede porque no tienen la fisma forma.

2.5 Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
reshape()
transpose()

In [47]:
array3 = np.transpose(array2,(1,2,0))
print(array3)

[[[1 5 8]
  [0 7 8]
  [6 7 2]
  [4 0 0]
  [3 3 5]]

 [[4 2 0]
  [4 1 2]
  [3 2 7]
  [4 8 3]
  [7 4 6]]]


2.6 Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [49]:
suma= np.add(array1,array3)
print(suma)

[[[ 2 12 13]
  [ 7 12 11]
  [10 11  8]
  [10  3  3]
  [ 3  6 12]]

 [[ 7  7  5]
  [ 4  5  4]
  [10  8 12]
  [ 6 12 10]
  [ 8 11 11]]]


In [51]:
resta = np.subtract(array1,array3)
print(resta)

[[[ 0  2 -3]
  [ 7 -2 -5]
  [-2 -3  4]
  [ 2  3  3]
  [-3  0  2]]

 [[-1  3  5]
  [-4  3  0]
  [ 4  4 -2]
  [-2 -4  4]
  [-6  3 -1]]]
