In [10]:
import pandas as pd
import numpy as np

1 ¿Qué diferencia hay entre una serie y un dataframe?
Serie: es  columnas (una dimesión)
dataframe : es una estructura de datos multidimensional.


Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [11]:
valores=[7,5,9,3,11,15,20]
indices=["lunes","martes","miercoles","jueves","viernes","sabado","domingo"]

In [12]:
#A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

serie1=pd.Series(valores,index=indices)
print(serie1)

lunes         7
martes        5
miercoles     9
jueves        3
viernes      11
sabado       15
domingo      20
dtype: int64


In [13]:
#A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción 

zip1=list(zip(indices,valores))
print(zip1)

[('lunes', 7), ('martes', 5), ('miercoles', 9), ('jueves', 3), ('viernes', 11), ('sabado', 15), ('domingo', 20)]


In [14]:
diccionario = {}
for i, v, in zip1:
    diccionario[i]=v
print(diccionario)
    
    

{'lunes': 7, 'martes': 5, 'miercoles': 9, 'jueves': 3, 'viernes': 11, 'sabado': 15, 'domingo': 20}


In [15]:
#Crea una Serie con el diccionario creado en el punto anterior.

serie2=pd.Series(diccionario)
print(serie2)
# nos salen iguales porque con el zip ordemanos los indices y los values para que nos diera un resultado ordenado.

lunes         7
martes        5
miercoles     9
jueves        3
viernes      11
sabado       15
domingo      20
dtype: int64


In [16]:
# que tamaño tiene?
#¿Qué forma tiene esta última Serie?
# que tipo de datos tiene?
serie2
print(serie2.size)
print(serie2.shape)
print(serie2.dtypes)

7
(7,)
int64


In [17]:
#Extraed el valor para el índice "lunes"
serie2["lunes"]

7

In [18]:
#Extraed el valor para el índice "lunes", "martes" y "miércoles".
serie2["lunes":"miercoles"]

lunes        7
martes       5
miercoles    9
dtype: int64

In [19]:
#Extraed el valor para el índice "lunes" y "domingo".
serie2[["lunes","domingo"]]

lunes       7
domingo    20
dtype: int64

ejercicio3 Es el turno de los DataFrames:
Cread un array de dos dimensiones con 4 filas y 3 columnas.

In [20]:
array=np.random.randint(0,9,(4,3))
print(array)

[[7 2 5]
 [1 2 2]
 [0 2 5]
 [6 0 3]]


Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [21]:
datafr=pd.DataFrame(array,columns=["España","Francia","Italia"])
print(datafr)

   España  Francia  Italia
0       7        2       5
1       1        2       2
2       0        2       5
3       6        0       3


In [22]:
df = pd.read_csv("_medallas.csv", index_col=["País"])

In [23]:
print(df)

                 Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235


In [24]:
df.loc["Tailandia"]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

In [25]:
df.loc[["China","Irán"]]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [26]:
df.loc[["China","Irán"],["Oro","Plata","Bronce"]] # Hace falta poner todos los valores de las columnas

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [27]:
df.iloc[5]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [28]:
df.iloc[1::2]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [29]:
df.iloc[1::2,1:]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

Contestad a las siguientes preguntas:
¿Qué país consiguió más de 200 medallas de oro?
¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?


In [30]:
df.loc[(df.Oro > 200)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [31]:
df.loc[(df.Oro >200)&(df.Plata>1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [32]:
df.loc[(df.Oro >200)&(df.Bronce>700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [33]:
df.assign(Total=df['Oro'] + df["Plata"]+df["Bronce"])

Unnamed: 0   Oro  Plata  Bronce  Total
País                                                   
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446

In [35]:
df.pop("Unnamed: 0")

País
China               1
Japón               2
Corea del Sur       3
Irán                4
Kazajistán          5
India               6
Tailandia           7
Indonesia           8
China Taipéi        9
Corea del Norte    10
Name: Unnamed: 0, dtype: int64

In [37]:
df.assign(Total=df['Oro'] + df["Plata"]+df["Bronce"])

Oro  Plata  Bronce  Total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446