In [1]:
import numpy as np
import pandas as pd


Ejercicio1-Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
 -El valor de la primera fila y la segunda columna.


In [2]:
array = np.random.rand(5,3) 
print(array)

[[0.47530445 0.93406041 0.44339896]
 [0.21998341 0.32703456 0.50635592]
 [0.51938261 0.91572055 0.35158447]
 [0.65581631 0.66290454 0.33004635]
 [0.76856333 0.99591284 0.29752953]]


In [3]:
array[0,1]

0.93406041046851

1.1 Los valores de la segunda fila y las dos primeras columnas.

In [4]:
array[1,:2]

array([0.21998341, 0.32703456])

1.2 Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [5]:
array[::2,:]

array([[0.47530445, 0.93406041, 0.44339896],
       [0.51938261, 0.91572055, 0.35158447],
       [0.76856333, 0.99591284, 0.29752953]])

1.3 Extraed los valores que sean mayores que 0.5.

In [6]:
array[array > 0.5]

array([0.93406041, 0.50635592, 0.51938261, 0.91572055, 0.65581631,
       0.66290454, 0.76856333, 0.99591284])

1.4 Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
array[(array<0.2)|(array>0.5)]

array([0.93406041, 0.50635592, 0.51938261, 0.91572055, 0.65581631,
       0.66290454, 0.76856333, 0.99591284])

Ejercicio2-Cread dos array de tres dimensiones:

2.1 El primero de 2 matrices, 5 filas y 3 columnas.

In [8]:
array1 = np.random.randint(0,9,(2,5,3))
print(array1)

[[[3 8 1]
  [5 6 0]
  [1 7 2]
  [5 0 1]
  [7 4 1]]

 [[8 5 4]
  [5 6 1]
  [6 7 6]
  [8 5 5]
  [7 8 4]]]


2.2 El segundo de 3 matrices, 2 filas y 5 columnas

In [9]:
array2 = np.random.randint(0,9,(3,2,5))
print(array2)

[[[8 5 4 5 4]
  [6 5 2 4 0]]

 [[2 1 7 7 5]
  [1 5 8 2 0]]

 [[8 2 3 7 5]
  [8 5 4 7 5]]]


2.3 Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [10]:
def analisis(miarray):
    return miarray.shape, miarray.size, miarray.dtype

In [11]:
print(analisis(array1))

analisis(array2)

((2, 5, 3), 30, dtype('int64'))


((3, 2, 5), 30, dtype('int64'))

2.4 Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [12]:
# no se puede porque no tienen la misma forma.

2.5 Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
reshape()
transpose()

In [13]:
array3 = np.transpose(array2,(1,2,0))
print(array3)

[[[8 2 8]
  [5 1 2]
  [4 7 3]
  [5 7 7]
  [4 5 5]]

 [[6 1 8]
  [5 5 5]
  [2 8 4]
  [4 2 7]
  [0 0 5]]]


2.6 Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [14]:
suma= np.add(array1,array3)
print(suma)

[[[11 10  9]
  [10  7  2]
  [ 5 14  5]
  [10  7  8]
  [11  9  6]]

 [[14  6 12]
  [10 11  6]
  [ 8 15 10]
  [12  7 12]
  [ 7  8  9]]]


In [15]:
resta = np.subtract(array1,array3)
print(resta)

[[[-5  6 -7]
  [ 0  5 -2]
  [-3  0 -1]
  [ 0 -7 -6]
  [ 3 -1 -4]]

 [[ 2  4 -4]
  [ 0  1 -4]
  [ 4 -1  2]
  [ 4  3 -2]
  [ 7  8 -1]]]
